// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_EngineManagementGauge = NULL;
lv_obj_t * ui_EngineLoadBar = NULL;
lv_obj_t * ui_EngineLoadLabel = NULL;
lv_obj_t * ui_EngineLoadValue = NULL;
lv_obj_t * ui_MAFLabel = NULL;
lv_obj_t * ui_MAFValue = NULL;
lv_obj_t * ui_MAFBar = NULL;
lv_obj_t * ui_ThrottleLabel = NULL;
lv_obj_t * ui_ThrottleValue = NULL;
lv_obj_t * ui_ThrottleBar = NULL;
lv_obj_t * ui_VoltLabel = NULL;
lv_obj_t * ui_VoltValue = NULL;
// event funtions
void ui_event_EngineManagementGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_RpmSpeedGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_RpmSpeedGauge_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_OilWaterTemperatureGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0,
                          &ui_OilWaterTemperatureGauge_screen_init);
    }
}

// build funtions

void ui_EngineManagementGauge_screen_init(void)
{
    ui_EngineManagementGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EngineManagementGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EngineManagementGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineManagementGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EngineLoadBar = lv_slider_create(ui_EngineManagementGauge);
    lv_slider_set_value(ui_EngineLoadBar, 15, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_EngineLoadBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_EngineLoadBar, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_EngineLoadBar, 180);
    lv_obj_set_height(ui_EngineLoadBar, 20);
    lv_obj_set_x(ui_EngineLoadBar, 0);
    lv_obj_set_y(ui_EngineLoadBar, -57);
    lv_obj_set_align(ui_EngineLoadBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EngineLoadBar, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_EngineLoadBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EngineLoadBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineLoadBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_EngineLoadBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EngineLoadBar, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineLoadBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_EngineLoadBar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineLoadBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_EngineLoadLabel = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_EngineLoadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EngineLoadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EngineLoadLabel, -25);
    lv_obj_set_y(ui_EngineLoadLabel, -79);
    lv_obj_set_align(ui_EngineLoadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EngineLoadLabel, "ENGINE LOAD");
    lv_obj_set_style_text_font(ui_EngineLoadLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EngineLoadValue = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_EngineLoadValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EngineLoadValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EngineLoadValue, 52);
    lv_obj_set_y(ui_EngineLoadValue, -79);
    lv_obj_set_align(ui_EngineLoadValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EngineLoadValue, "15%");

    ui_MAFLabel = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_MAFLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAFLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAFLabel, -24);
    lv_obj_set_y(ui_MAFLabel, -22);
    lv_obj_set_align(ui_MAFLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAFLabel, "MAF g/s");

    ui_MAFValue = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_MAFValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAFValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAFValue, 30);
    lv_obj_set_y(ui_MAFValue, -22);
    lv_obj_set_align(ui_MAFValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAFValue, "3");

    ui_MAFBar = lv_slider_create(ui_EngineManagementGauge);
    lv_slider_set_range(ui_MAFBar, 0, 20);
    lv_slider_set_value(ui_MAFBar, 3, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MAFBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MAFBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MAFBar, 180);
    lv_obj_set_height(ui_MAFBar, 20);
    lv_obj_set_align(ui_MAFBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MAFBar, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_MAFBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MAFBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MAFBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_MAFBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MAFBar, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MAFBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MAFBar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MAFBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ThrottleLabel = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_ThrottleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrottleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThrottleLabel, -24);
    lv_obj_set_y(ui_ThrottleLabel, 30);
    lv_obj_set_align(ui_ThrottleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrottleLabel, "THROTTLE");

    ui_ThrottleValue = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_ThrottleValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThrottleValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThrottleValue, 34);
    lv_obj_set_y(ui_ThrottleValue, 30);
    lv_obj_set_align(ui_ThrottleValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThrottleValue, "0%");

    ui_ThrottleBar = lv_slider_create(ui_EngineManagementGauge);
    lv_slider_set_value(ui_ThrottleBar, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ThrottleBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ThrottleBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_ThrottleBar, 180);
    lv_obj_set_height(ui_ThrottleBar, 20);
    lv_obj_set_x(ui_ThrottleBar, 0);
    lv_obj_set_y(ui_ThrottleBar, 52);
    lv_obj_set_align(ui_ThrottleBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThrottleBar, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_ThrottleBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThrottleBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrottleBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ThrottleBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ThrottleBar, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrottleBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ThrottleBar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ThrottleBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VoltLabel = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_VoltLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltLabel, -21);
    lv_obj_set_y(ui_VoltLabel, 88);
    lv_obj_set_align(ui_VoltLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltLabel, "Volts");
    lv_obj_set_style_text_font(ui_VoltLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltValue = lv_label_create(ui_EngineManagementGauge);
    lv_obj_set_width(ui_VoltValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VoltValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VoltValue, 20);
    lv_obj_set_y(ui_VoltValue, 88);
    lv_obj_set_align(ui_VoltValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VoltValue, "12");
    lv_obj_set_style_text_font(ui_VoltValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_EngineManagementGauge, ui_event_EngineManagementGauge, LV_EVENT_ALL, NULL);

}

void ui_EngineManagementGauge_screen_destroy(void)
{
    if(ui_EngineManagementGauge) lv_obj_del(ui_EngineManagementGauge);

    // NULL screen variables
    ui_EngineManagementGauge = NULL;
    ui_EngineLoadBar = NULL;
    ui_EngineLoadLabel = NULL;
    ui_EngineLoadValue = NULL;
    ui_MAFLabel = NULL;
    ui_MAFValue = NULL;
    ui_MAFBar = NULL;
    ui_ThrottleLabel = NULL;
    ui_ThrottleValue = NULL;
    ui_ThrottleBar = NULL;
    ui_VoltLabel = NULL;
    ui_VoltValue = NULL;

}
