// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_EngineHealthGauge = NULL;
lv_obj_t * ui_STFT1Label = NULL;
lv_obj_t * ui_STFT2Label = NULL;
lv_obj_t * ui_STFT1Value = NULL;
lv_obj_t * ui_STFT2Value = NULL;
lv_obj_t * ui_AnticipoLabel = NULL;
lv_obj_t * ui_AnticipoValue = NULL;
lv_obj_t * ui_TempAriaLabel = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_TempCat1Label = NULL;
lv_obj_t * ui_TempCat1Value = NULL;
lv_obj_t * ui_TempCat2Label = NULL;
lv_obj_t * ui_TempCat2Value = NULL;
lv_obj_t * ui_PressBarLabel = NULL;
lv_obj_t * ui_PressBarValue = NULL;
// event funtions
void ui_event_EngineHealthGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_OilWaterTemperatureGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0,
                          &ui_OilWaterTemperatureGauge_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_RpmSpeedGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_RpmSpeedGauge_screen_init);
    }
}

// build funtions

void ui_EngineHealthGauge_screen_init(void)
{
    ui_EngineHealthGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EngineHealthGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EngineHealthGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineHealthGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STFT1Label = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_STFT1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STFT1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STFT1Label, -63);
    lv_obj_set_y(ui_STFT1Label, -78);
    lv_obj_set_align(ui_STFT1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STFT1Label, "STFT 1:");

    ui_STFT2Label = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_STFT2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STFT2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STFT2Label, 26);
    lv_obj_set_y(ui_STFT2Label, -78);
    lv_obj_set_align(ui_STFT2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STFT2Label, "STFT 2:");

    ui_STFT1Value = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_STFT1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STFT1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STFT1Value, -21);
    lv_obj_set_y(ui_STFT1Value, -78);
    lv_obj_set_align(ui_STFT1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STFT1Value, "10%");

    ui_STFT2Value = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_STFT2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STFT2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STFT2Value, 70);
    lv_obj_set_y(ui_STFT2Value, -78);
    lv_obj_set_align(ui_STFT2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STFT2Value, "10%");

    ui_AnticipoLabel = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_AnticipoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnticipoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnticipoLabel, -69);
    lv_obj_set_y(ui_AnticipoLabel, -46);
    lv_obj_set_align(ui_AnticipoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnticipoLabel, "ANTICIPO:");

    ui_AnticipoValue = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_AnticipoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnticipoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnticipoValue, -22);
    lv_obj_set_y(ui_AnticipoValue, -46);
    lv_obj_set_align(ui_AnticipoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnticipoValue, "5°");

    ui_TempAriaLabel = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_TempAriaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempAriaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempAriaLabel, 30);
    lv_obj_set_y(ui_TempAriaLabel, -46);
    lv_obj_set_align(ui_TempAriaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempAriaLabel, "TEMP.ARIA:");

    ui_Label8 = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 88);
    lv_obj_set_y(ui_Label8, -45);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "40°C");

    ui_TempCat1Label = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_TempCat1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCat1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCat1Label, -37);
    lv_obj_set_y(ui_TempCat1Label, -12);
    lv_obj_set_align(ui_TempCat1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCat1Label, "TEMP.CAT1:");

    ui_TempCat1Value = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_TempCat1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCat1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCat1Value, 33);
    lv_obj_set_y(ui_TempCat1Value, -12);
    lv_obj_set_align(ui_TempCat1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCat1Value, "300°C");

    ui_TempCat2Label = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_TempCat2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCat2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCat2Label, -38);
    lv_obj_set_y(ui_TempCat2Label, 8);
    lv_obj_set_align(ui_TempCat2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCat2Label, "TEMP.CAT2:");

    ui_TempCat2Value = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_TempCat2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCat2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCat2Value, 33);
    lv_obj_set_y(ui_TempCat2Value, 8);
    lv_obj_set_align(ui_TempCat2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempCat2Value, "300°C");

    ui_PressBarLabel = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_PressBarLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressBarLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressBarLabel, -33);
    lv_obj_set_y(ui_PressBarLabel, 34);
    lv_obj_set_align(ui_PressBarLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressBarLabel, "Press.Bar:");

    ui_PressBarValue = lv_label_create(ui_EngineHealthGauge);
    lv_obj_set_width(ui_PressBarValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressBarValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressBarValue, 34);
    lv_obj_set_y(ui_PressBarValue, 35);
    lv_obj_set_align(ui_PressBarValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressBarValue, "90kPa");

    lv_obj_add_event_cb(ui_EngineHealthGauge, ui_event_EngineHealthGauge, LV_EVENT_ALL, NULL);

}

void ui_EngineHealthGauge_screen_destroy(void)
{
    if(ui_EngineHealthGauge) lv_obj_del(ui_EngineHealthGauge);

    // NULL screen variables
    ui_EngineHealthGauge = NULL;
    ui_STFT1Label = NULL;
    ui_STFT2Label = NULL;
    ui_STFT1Value = NULL;
    ui_STFT2Value = NULL;
    ui_AnticipoLabel = NULL;
    ui_AnticipoValue = NULL;
    ui_TempAriaLabel = NULL;
    ui_Label8 = NULL;
    ui_TempCat1Label = NULL;
    ui_TempCat1Value = NULL;
    ui_TempCat2Label = NULL;
    ui_TempCat2Value = NULL;
    ui_PressBarLabel = NULL;
    ui_PressBarValue = NULL;

}
