// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ENGINEMANAGEMENTGAUGE_H
#define UI_ENGINEMANAGEMENTGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EngineManagementGauge
extern void ui_EngineManagementGauge_screen_init(void);
extern void ui_EngineManagementGauge_screen_destroy(void);
extern void ui_event_EngineManagementGauge(lv_event_t * e);
extern lv_obj_t * ui_EngineManagementGauge;
extern lv_obj_t * ui_EngineLoadBar;
extern lv_obj_t * ui_EngineLoadLabel;
extern lv_obj_t * ui_EngineLoadValue;
extern lv_obj_t * ui_MAFLabel;
extern lv_obj_t * ui_MAFValue;
extern lv_obj_t * ui_MAFBar;
extern lv_obj_t * ui_ThrottleLabel;
extern lv_obj_t * ui_ThrottleValue;
extern lv_obj_t * ui_ThrottleBar;
extern lv_obj_t * ui_VoltLabel;
extern lv_obj_t * ui_VoltValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

