// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MiscGauge = NULL;
lv_obj_t * ui_MLogo = NULL;
// event funtions

// build funtions

void ui_MiscGauge_screen_init(void)
{
    ui_MiscGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MiscGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MiscGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MiscGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MLogo = lv_img_create(ui_MiscGauge);
    lv_img_set_src(ui_MLogo, &ui_img_724913057);
    lv_obj_set_width(ui_MLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MLogo, 200);

}

void ui_MiscGauge_screen_destroy(void)
{
    if(ui_MiscGauge) lv_obj_del(ui_MiscGauge);

    // NULL screen variables
    ui_MiscGauge = NULL;
    ui_MLogo = NULL;

}
