// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MISCGAUGE_H
#define UI_MISCGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MiscGauge
extern void ui_MiscGauge_screen_init(void);
extern void ui_MiscGauge_screen_destroy(void);
extern void ui_event_MiscGauge(lv_event_t * e);
extern lv_obj_t * ui_MiscGauge;
extern lv_obj_t * ui_MLogo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

