// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_OILWATERTEMPERATUREGAUGE_H
#define UI_OILWATERTEMPERATUREGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OilWaterTemperatureGauge
extern void ui_OilWaterTemperatureGauge_screen_init(void);
extern void ui_OilWaterTemperatureGauge_screen_destroy(void);
extern void ui_event_OilWaterTemperatureGauge(lv_event_t * e);
extern lv_obj_t * ui_OilWaterTemperatureGauge;
extern lv_obj_t * ui_OilLabel;
extern void ui_event_OilTemperatureArc(lv_event_t * e);
extern lv_obj_t * ui_OilTemperatureArc;
extern void ui_event_WaterTemperatureArc(lv_event_t * e);
extern lv_obj_t * ui_WaterTemperatureArc;
extern lv_obj_t * ui_OilTemperatureLabel;
extern lv_obj_t * ui_WaterTemperatureLabel;
extern lv_obj_t * ui_OilTemperatureValue;
extern lv_obj_t * ui_WaterTemperatureValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

