// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_ENGINEHEALTHGAUGE_H
#define UI_ENGINEHEALTHGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EngineHealthGauge
extern void ui_EngineHealthGauge_screen_init(void);
extern void ui_EngineHealthGauge_screen_destroy(void);
extern void ui_event_EngineHealthGauge(lv_event_t * e);
extern lv_obj_t * ui_EngineHealthGauge;
extern lv_obj_t * ui_STFT1Label;
extern lv_obj_t * ui_STFT2Label;
extern lv_obj_t * ui_STFT1Value;
extern lv_obj_t * ui_STFT2Value;
extern lv_obj_t * ui_AnticipoLabel;
extern lv_obj_t * ui_AnticipoValue;
extern lv_obj_t * ui_TempAriaLabel;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TempCat1Label;
extern lv_obj_t * ui_TempCat1Value;
extern lv_obj_t * ui_TempCat2Label;
extern lv_obj_t * ui_TempCat2Value;
extern lv_obj_t * ui_PressBarLabel;
extern lv_obj_t * ui_PressBarValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

