// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_OilWaterTemperatureGauge = NULL;
lv_obj_t * ui_OilLabel = NULL;
lv_obj_t * ui_OilTemperatureArc = NULL;
lv_obj_t * ui_WaterTemperatureArc = NULL;
lv_obj_t * ui_OilTemperatureLabel = NULL;
lv_obj_t * ui_WaterTemperatureLabel = NULL;
lv_obj_t * ui_OilTemperatureValue = NULL;
lv_obj_t * ui_WaterTemperatureValue = NULL;
// event funtions
void ui_event_OilWaterTemperatureGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_EngineManagementGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_EngineManagementGauge_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_RpmSpeedGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_RpmSpeedGauge_screen_init);
    }
}

void ui_event_OilTemperatureArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_OilTemperatureValue, target, "", "");
    }
}

void ui_event_WaterTemperatureArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_WaterTemperatureValue, target, "", "");
    }
}

// build funtions

void ui_OilWaterTemperatureGauge_screen_init(void)
{
    ui_OilWaterTemperatureGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OilWaterTemperatureGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OilWaterTemperatureGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OilWaterTemperatureGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilLabel = lv_label_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_OilLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilLabel, -52);
    lv_obj_set_y(ui_OilLabel, -43);
    lv_obj_set_align(ui_OilLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OilLabel, "OIL C°");
    lv_obj_set_style_text_color(ui_OilLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OilLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OilLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilTemperatureArc = lv_arc_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_OilTemperatureArc, 220);
    lv_obj_set_height(ui_OilTemperatureArc, 220);
    lv_obj_set_align(ui_OilTemperatureArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OilTemperatureArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_OilTemperatureArc, 0, 180);
    lv_arc_set_value(ui_OilTemperatureArc, 90);
    lv_arc_set_bg_angles(ui_OilTemperatureArc, 185, 355);
    lv_obj_set_style_radius(ui_OilTemperatureArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_OilTemperatureArc, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_OilTemperatureArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_OilTemperatureArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_OilTemperatureArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_OilTemperatureArc, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_OilTemperatureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_OilTemperatureArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_OilTemperatureArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OilTemperatureArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OilTemperatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_WaterTemperatureArc = lv_arc_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_WaterTemperatureArc, 220);
    lv_obj_set_height(ui_WaterTemperatureArc, 220);
    lv_obj_set_align(ui_WaterTemperatureArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WaterTemperatureArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_WaterTemperatureArc, 0, 180);
    lv_arc_set_value(ui_WaterTemperatureArc, 90);
    lv_arc_set_bg_angles(ui_WaterTemperatureArc, 185, 355);
    lv_arc_set_mode(ui_WaterTemperatureArc, LV_ARC_MODE_REVERSE);
    lv_arc_set_rotation(ui_WaterTemperatureArc, 180);
    lv_obj_set_style_radius(ui_WaterTemperatureArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_WaterTemperatureArc, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterTemperatureArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WaterTemperatureArc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_WaterTemperatureArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_WaterTemperatureArc, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterTemperatureArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WaterTemperatureArc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_WaterTemperatureArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WaterTemperatureArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaterTemperatureArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_OilTemperatureLabel = lv_label_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_OilTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilTemperatureLabel, 0);
    lv_obj_set_y(ui_OilTemperatureLabel, -73);
    lv_obj_set_align(ui_OilTemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OilTemperatureLabel, "OIL °C");
    lv_obj_set_style_text_font(ui_OilTemperatureLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTemperatureLabel = lv_label_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_WaterTemperatureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterTemperatureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterTemperatureLabel, 0);
    lv_obj_set_y(ui_WaterTemperatureLabel, 64);
    lv_obj_set_align(ui_WaterTemperatureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WaterTemperatureLabel, "WATER °C");
    lv_obj_set_style_text_font(ui_WaterTemperatureLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OilTemperatureValue = lv_label_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_OilTemperatureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OilTemperatureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OilTemperatureValue, 0);
    lv_obj_set_y(ui_OilTemperatureValue, -37);
    lv_obj_set_align(ui_OilTemperatureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OilTemperatureValue, "90");
    lv_obj_set_style_text_font(ui_OilTemperatureValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTemperatureValue = lv_label_create(ui_OilWaterTemperatureGauge);
    lv_obj_set_width(ui_WaterTemperatureValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WaterTemperatureValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterTemperatureValue, 0);
    lv_obj_set_y(ui_WaterTemperatureValue, 29);
    lv_obj_set_align(ui_WaterTemperatureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WaterTemperatureValue, "90");
    lv_obj_set_style_text_font(ui_WaterTemperatureValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OilTemperatureArc, ui_event_OilTemperatureArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WaterTemperatureArc, ui_event_WaterTemperatureArc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OilWaterTemperatureGauge, ui_event_OilWaterTemperatureGauge, LV_EVENT_ALL, NULL);

}

void ui_OilWaterTemperatureGauge_screen_destroy(void)
{
    if(ui_OilWaterTemperatureGauge) lv_obj_del(ui_OilWaterTemperatureGauge);

    // NULL screen variables
    ui_OilWaterTemperatureGauge = NULL;
    ui_OilLabel = NULL;
    ui_OilTemperatureArc = NULL;
    ui_WaterTemperatureArc = NULL;
    ui_OilTemperatureLabel = NULL;
    ui_WaterTemperatureLabel = NULL;
    ui_OilTemperatureValue = NULL;
    ui_WaterTemperatureValue = NULL;

}
