// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_RPMSPEEDGAUGE_H
#define UI_RPMSPEEDGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RpmSpeedGauge
extern void ui_RpmSpeedGauge_screen_init(void);
extern void ui_RpmSpeedGauge_screen_destroy(void);
extern void ui_event_RpmSpeedGauge(lv_event_t * e);
extern lv_obj_t * ui_RpmSpeedGauge;
extern lv_obj_t * ui_RPMValue;
extern void ui_event_RPMBar(lv_event_t * e);
extern lv_obj_t * ui_RPMBar;
extern lv_obj_t * ui_KMHValue;
extern lv_obj_t * ui_KMHLabel;
extern lv_obj_t * ui_EngineLoadValue2;
extern lv_obj_t * ui_EngineTorqueValue;
extern lv_obj_t * ui_HPValue;
extern void ui_event_EngineLoadArc(lv_event_t * e);
extern lv_obj_t * ui_EngineLoadArc;
extern void ui_event_EngineHpArc(lv_event_t * e);
extern lv_obj_t * ui_EngineHpArc;
extern void ui_event_EngineTorqueArc(lv_event_t * e);
extern lv_obj_t * ui_EngineTorqueArc;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

