// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_RpmSpeedGauge = NULL;
lv_obj_t * ui_RPMValue = NULL;
lv_obj_t * ui_RPMBar = NULL;
lv_obj_t * ui_KMHValue = NULL;
lv_obj_t * ui_KMHLabel = NULL;
// event funtions
void ui_event_RpmSpeedGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_OilWaterTemperatureGauge, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0,
                          &ui_OilWaterTemperatureGauge_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_EngineManagementGauge, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0,
                          &ui_EngineManagementGauge_screen_init);
    }
}

void ui_event_RPMBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_RPMValue, target, "", "");
    }
}

// build funtions

void ui_RpmSpeedGauge_screen_init(void)
{
    ui_RpmSpeedGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RpmSpeedGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RpmSpeedGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmSpeedGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMValue = lv_label_create(ui_RpmSpeedGauge);
    lv_obj_set_width(ui_RPMValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMValue, 0);
    lv_obj_set_y(ui_RPMValue, -90);
    lv_obj_set_align(ui_RPMValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMValue, "700");
    lv_obj_set_style_text_font(ui_RPMValue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMBar = lv_slider_create(ui_RpmSpeedGauge);
    lv_slider_set_range(ui_RPMBar, 0, 6500);
    lv_slider_set_value(ui_RPMBar, 700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_RPMBar) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_RPMBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMBar, 170);
    lv_obj_set_height(ui_RPMBar, 30);
    lv_obj_set_x(ui_RPMBar, 0);
    lv_obj_set_y(ui_RPMBar, -49);
    lv_obj_set_align(ui_RPMBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPMBar, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPMBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBar, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBar, lv_color_hex(0x00B432), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPMBar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KMHValue = lv_label_create(ui_RpmSpeedGauge);
    lv_obj_set_width(ui_KMHValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KMHValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KMHValue, 0);
    lv_obj_set_y(ui_KMHValue, 28);
    lv_obj_set_align(ui_KMHValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KMHValue, "0");
    lv_obj_set_style_text_font(ui_KMHValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KMHLabel = lv_label_create(ui_RpmSpeedGauge);
    lv_obj_set_width(ui_KMHLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KMHLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KMHLabel, 0);
    lv_obj_set_y(ui_KMHLabel, 80);
    lv_obj_set_align(ui_KMHLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KMHLabel, "KMH");
    lv_obj_set_style_text_font(ui_KMHLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RPMBar, ui_event_RPMBar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RpmSpeedGauge, ui_event_RpmSpeedGauge, LV_EVENT_ALL, NULL);

}

void ui_RpmSpeedGauge_screen_destroy(void)
{
    if(ui_RpmSpeedGauge) lv_obj_del(ui_RpmSpeedGauge);

    // NULL screen variables
    ui_RpmSpeedGauge = NULL;
    ui_RPMValue = NULL;
    ui_RPMBar = NULL;
    ui_KMHValue = NULL;
    ui_KMHLabel = NULL;

}
